spring:
  application:
    name: order-service

server:
  port: 8080

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf

  logs:
    level: INFO
    exporter: none

  resource:
    attributes:
      service.name: order-service

  traces:
    sampler:
      probability: 1.0
    always-on: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{trace_id},spanId=%X{span_id}]"
